# -*- coding: utf-8 -*-
"""Untitled164.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KvtEGenfnnKVuOJ6tT6g8dMTGYhTD1PQ
"""

import streamlit as st
import pandas as pd

# Função para calcular os campos derivados
def calcular_campos(df):
    df['Preço Total'] = df.apply(lambda row: row['S. E. O'] + row['Prêmio / Desc.'] if row['Quantidade Fixada'] > 0 else 0, axis=1)
    df['Saldo a Fixar'] = df['QTD. VENDIDA'] - df['Quantidade Fixada']
    df['Lotes a fixar'] = df['Saldo a Fixar'] / 50.8
    df['SEO x Quant. Fixadas'] = df['S. E. O'] * df['Quantidade Fixada']
    df['Prêmio x Quant. Fixadas'] = df['Prêmio / Desc.'] * df['Quantidade Fixada']
    df['Preço x Quant. Fixadas'] = df['Preço Total'] * df['Quantidade Fixada']
    df['Prêmio x Quant. Vendidas'] = df['Prêmio / Desc.'] * df['QTD. VENDIDA']
    return df

# Verificar se o arquivo CSV já existe, se não, criar um DataFrame vazio
try:
    df = pd.read_csv('contratos.csv')
except FileNotFoundError:
    df = pd.DataFrame(columns=['COMPRADOR', 'CONTRATO', 'QTD. VENDIDA', 'MÊS DE FIXAÇÃO', 'Quantidade Fixada', 'S. E. O', 'Prêmio / Desc.', 'PERÍODO DE EMBARQUE', 'Cessão'])

# Página de cadastro de contrato
st.title('Cadastro de Contrato')

comprador = st.text_input('Comprador')
contrato = st.text_input('Contrato')
qtd_vendida = st.number_input('Quantidade Vendida (tm)', min_value=0.0)
mes_fixacao = st.text_input('Mês de Fixação')
quantidade_fixada = st.number_input('Quantidade Fixada (tm)', min_value=0.0)
seo = st.number_input('S. E. O', min_value=0.0)
premio_desc = st.number_input('Prêmio / Desc.', min_value=0.0)
periodo_embarque = st.date_input('Período de Embarque', (pd.to_datetime('today'), pd.to_datetime('today')))
cessao = st.text_input('Cessão (opcional)')

if st.button('Concluir Cadastro'):
    novo_contrato = pd.DataFrame({'COMPRADOR': [comprador], 'CONTRATO': [contrato], 'QTD. VENDIDA': [qtd_vendida], 'MÊS DE FIXAÇÃO': [mes_fixacao], 'Quantidade Fixada': [quantidade_fixada], 'S. E. O': [seo], 'Prêmio / Desc.': [premio_desc], 'PERÍODO DE EMBARQUE': [periodo_embarque], 'Cessão': [cessao]})
    df = pd.concat([df, novo_contrato], ignore_index=True)
    df = calcular_campos(df)
    df.to_excel('contratos.xlsx', index=False)  # Salvar como Excel
    st.success('Contrato cadastrado com sucesso!')

# Página de mudança de contrato
st.title('Mudança de Contrato')

contrato_selecionado = st.text_input('Digite o contrato a ser alterado ou excluído')
contratos_info = df[df['CONTRATO'] == contrato_selecionado]

if not contratos_info.empty:
    st.write('Informações do(s) contrato(s) encontrado(s):')
    st.write(contratos_info)

    if len(contratos_info) > 1:
        contrato_escolhido = st.selectbox('Escolha o contrato a ser modificado ou excluído', contratos_info['CONTRATO'].unique())
        contrato_info = contratos_info[contratos_info['CONTRATO'] == contrato_escolhido].iloc[0]
    else:
        contrato_info = contratos_info.iloc[0]

    colunas_para_alterar = st.multiselect('Selecione as colunas para alterar', contrato_info.index)

    if st.button('Alterar'):
        for coluna in colunas_para_alterar:
            novo_valor = st.text_input(f'Novo valor para {coluna}', value=str(contrato_info[coluna]))
            contrato_info[coluna] = novo_valor

        df.loc[df['CONTRATO'] == contrato_info['CONTRATO'], contrato_info.index] = contrato_info
        df = calcular_campos(df)
        df.to_excel('contratos.xlsx', index=False)  # Salvar como Excel
        st.success('Contrato alterado com sucesso!')

    if st.button('Excluir'):
        df = df[df['CONTRATO'] != contrato_info['CONTRATO']]
        df = calcular_campos(df)
        df.to_excel('contratos.xlsx', index=False)  # Salvar como Excel
        st.success('Contrato excluído com sucesso!')

else:
    st.warning('Contrato não encontrado.')

# Página de visualização e download de arquivos
st.title('Visualização e Download de Arquivos')

st.write(df)

st.write('Para fazer o download do arquivo Excel, clique no link abaixo:')
st.markdown('[Download Excel](contratos.xlsx)')
